feat(infer): リリースWorkflowにバージョンのバリデーションを追加、Releasesに上げる条件を変更 (#62)
Co-authored-by: Hiroshiba <hihokaruta@gmail.com>

diff --git a/.github/workflows/build_and_deploy_infer.yml b/.github/workflows/build_and_deploy_infer.yml
--- a/.github/workflows/build_and_deploy_infer.yml
+++ b/.github/workflows/build_and_deploy_infer.yml
@@ -7,7 +7,7 @@ on:
         description: "バージョン情報（A.BB.C / A.BB.C-preview.D）"
         required: true
       production:
-        description: "falseならTestPyPIにデプロイ、trueならpypi EnvironmentでPyPIにデプロイ"
+        description: "falseならTestPyPIにデプロイ、trueならpypi EnvironmentでPyPIとGitHubのReleasesにデプロイ"
         type: boolean
         required: false
         default: false
@@ -18,7 +18,23 @@ defaults:
     working-directory: infer
 
 jobs:
+  # TODO: 入力のパースとそれに従った値の分岐をconfigというjobにまとめる
+  validate:
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Validate version
+        run: |
+          if [[ "${{ inputs.version }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+(-preview\.[0-9]+)?$ ]]; then
+            echo "Valid version format"
+          else
+            echo "Invalid version format. Expected A.BB.C or A.BB.C-preview.D"
+            exit 1
+          fi
+
   build:
+    needs:
+      - validate
     strategy:
       fail-fast: false
       matrix:
@@ -93,9 +109,11 @@ jobs:
           verbose: true
 
       - name: Create release
+        if: inputs.production
         uses: softprops/action-gh-release@v2
         with:
           tag_name: ${{ inputs.version }}
           target_commitish: ${{ github.sha }}
           draft: false
-          prerelease: ${{ !inputs.production }}
+          # A.BB.Cのみを正式リリースとする
+          prerelease: ${{ contains(inputs.version, '-') }}
